x-app: &app
  image: ghcr.io/shyim/example-shopware-docker-project:latest
  volumes:
    - files:/var/www/html/files
    - theme:/var/www/html/public/theme
    - media:/var/www/html/public/media
    - thumbnail:/var/www/html/public/thumbnail
    - sitemap:/var/www/html/public/sitemap
  environment:
    APP_ENV: prod
    APP_SECRET: '${APP_SECRET}'
    JWT_PRIVATE_KEY: '${JWT_PRIVATE_KEY}'
    JWT_PUBLIC_KEY: '${JWT_PUBLIC_KEY}'
    APP_URL: http://localhost
    DATABASE_HOST: db
    DATABASE_URL: mysql://shopware:${MYSQL_PASSWORD}@db/shopware

version: "3.8"
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_USER: shopware
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_DATABASE: shopware
            MYSQL_RANDOM_ROOT_PASSWORD: 1
        volumes:
          - mysql-data:/var/lib/mysql

    init-perm:
        image: alpine
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap

    init:
        <<: *app
        entrypoint: /setup
        depends_on:
            db:
                condition: service_started
            init-perm:
                condition: service_completed_successfully
    web:
        <<: *app
        depends_on:
            init:
                condition: service_completed_successfully
        ports:
            - 8000:8000

    worker:
        <<: *app
        restart: unless-stopped
        depends_on:
          init:
              condition: service_completed_successfully
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "--time-limit=300", "--memory-limit=512M" ]
        deploy:
          replicas: 3

volumes:
    mysql-data:
    files:
    theme:
    media:
    thumbnail:
    sitemap: